### ISSUE TITLE
Is GLi switching from OpenWRT to LEDE?

### ISSUE THREAD

**Issue by taoeffect** [domino-team/lede-1701#2]
So a few questions:

- Is GLi switching from OpenWRT to LEDE?
- If so, why?
- If so, will future firmware updates to existing devices (like the GL-AR300M) use this firmware instead of your fork of openwrt?

**Comment by alzhao** [comment]
Yes. Because nearly all OpenWrt developers goes to LEDE and original OpenWrt is dead already.
We will still use the old fork of openwrt for a while but we will shift to LEDE later.

**Comment by taoeffect** [comment]
OK thanks, I didn't know that "OpenWrt is dead already". Interesting.

Is this repo ready to be used on the GL-AR300M? Or is this still a work-in-progress and we should wait before attempting to update to this firmware ourselves?

**Comment by sholwe** [comment]
Yaaay!  I love the Domino OWRT builds, and I bet the LEDE ones will be just as tasty.

**Comment by alzhao** [comment]
OpenWrt and LEDE is re-merging. They will use OpenWrt as the name but use LEDE's source code.
