### ISSUE TITLE
mkimage: Can't map /vagrant//bin/AR300M/Images//printstation-ar71xx-generic-uImage-lzma.bin: Invalid argument

### ISSUE THREAD

**Issue by jcampbell05** [domino-team/lede-1701#4]
Currently getting this regarding the AR300M device.

**Comment by alzhao** [comment]
I just did a clear clone and tried to build both Nand and Nor fimrware and everything is fine. I didn't get the error you mentioned. I am using Ubuntu 16.04 64bit.

**Comment by jcampbell05** [comment]
Turned out this was due to me running this in a virtual machine and setting the export dir to a folder that was being rsynced by vagrant. Building the image in the VM and then copying the artifacts to the synced dir fixed the issue.
